/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'ICONS';
  static const String? _kFontPkg = null;

  static const IconData password = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData teams = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videoCall = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attatch = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData record = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData headphone = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mood = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);

}
